const mongoose=require('mongoose')
const Schema= mongoose.Schema

const ProfileSchema=new Schema({
    user:{
        type:Schema.Types.ObjectId,
        ref:"users"
    },
    handle:{
        type:String,
        required:false
    },
    company:{
        type:String,
        required:false
    },
    website:{
        type:String,
        required:false
    },
    location:{
        type:String,
        required:false
    },
    status:{
        type:String,
        required:false
    },
    skills:{
        type:[String],
        required:false
    },    
    bio:{
        type:String,
        required:false
    },
    githubusername:{
        type:String,
        required:false
    },    
    experience:[
        {
        current:{
            type:Boolean,
            default:true
        },
        title:{
            type:String,
            required:false
        }, 
        company:{
            type:String,
            required:false
        }, 
        location:{
            type:String,
            required:false
        }, 
        from:{
            type:String,
            required:false
        }, 
        to:{
            type:String,
            required:false
        }, 
        description:{
            type:String,
            required:false
        }
    },
    ], 
    education:[
        {
            current:{
            type:Boolean,
            default:true
            },
            school:{
            type:String,
            required:false
            }, 
            degree:{
                type:String,
                required:false
            }, 
            fieldofstudy:{
                type:String,
                required:false
            }, 
            from:{
                type:String,
                required:false
            }, 
            to:{
                type:String,
                required:false
            }, 
            description:{
                type:String,
                required:false
            }
        },
    ], 
    social:{
        wechat:{
            type:String,
            required:false
        }, 
        QQ:{
            type:String,
            required:false
        },
        wangyikt:{
            type:String,
            required:false
        },
        tengxunkt:{
            type:String,
            required:false
        },
    },   
    date:{
        type:Date,
        default:Date.now
    }

})

module.exports=Profile=mongoose.model("profile",ProfileSchema)